import { config } from "dotenv";

config();

export const { NODE_ENV, PORT, ACCESS_TOKEN_SECRET, REFRESH_TOKEN_SECRET, YOUTUBE_API_KEY, YOUTUBE_ENDPOINT,
    CLIENT_ID, CLIENT_SECRET, REDIRECT_URI, CLIENT_URL, MY_EMAIL, APP_PASSWORD, REPORT_HISTORY_URL,
    CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET, CLOUDINARY_CLOUD_NAME, SERVICE_ACCOUNT_KEY
} = process.env;